name: Daily Auto Commits Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  daily_auto_commits:
    name: Daily Auto Commits Job
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup git User
        run: |
          git config --global user.email "tolikgalas@gmail.com"
          git config --global user.name "Anatolii Halas"

      - name: Add changes and push
        run: |
          info="Commit - $(date)"
          echo "$info" >> output.txt
          git commit -am "$info"
          git push
