name: Daily Auto Commits Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  daily_auto_commits:
    name: Daily Auto Commits Job
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: tolikhalas/commit-bot

      - name: Setup git User
        run: |
          git config --global user.email "tolikgalas@gmail.com"
          git config --global user.name "Anatolii Halas"

      - name: Show remote url
        run: git remote get-url origin

      - name: Added changes and push
        env:
          token: ${{ secrets.ACTIONS_PAT }}
        run: |
          info="Commit - $(date)"
          echo "$info" >> output.txt
          git add output.txt
          git commit -m "$info"
          git push origin main
