name: Daily Auto Commits Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  daily_auto_commits:
    name: Daily Auto Commits Job
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup git User
        run: |
          git config --global user.email "tolikgalas@gmail.com"
          git config --global user.name "Anatolii Halas"

      - name: Get day of week
        id: day_of_week
        run: |
          WEEKDAY=$(date +%A)
          echo "::set-output name=weekday::$WEEKDAY"

      - name: Set min value based on day of week
        id: set_min_max_value
        run: |
          weekday=${{ steps.day_of_week.outputs.weekday }}
          if [ weekday == "Sunday" || weekday == "Saturday" ]; then
            echo "::set-output name=min::5"
            echo "::set-output name=max::25"
          else
            echo "::set-output name=min::25"
            echo "::set-output name=max::75"
          fi

      - name: Random number for commits
        id: random_number
        uses: yakubique/random-number@v1.1
        with:
          min: ${{ steps.set_min_max_value.outputs.min }}
          max: ${{ steps.set_min_max_value.outputs.max }}

      - name: Generate commits random number of times
        run: |
          number_of_commits=${{ steps.random_number.outputs.number }}
          for((i=0; i<number_of_commits; i++)); do
            info="Commit - $(date)"
            echo "$info" >> reports.txt
            git commit -am "$info"
            sleep 0.5
          done
          git push
