name: Daily Auto Commits Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  daily_auto_commits:
    name: Daily Auto Commits Job
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          repository: tolikhalas/commit-bot
          path: commit-bot
          fetch-depth: 0

      - name: Setup git User
        run: |
          git config --global user.email "tolikgalas@gmail.com"
          git config --global user.name "Anatolii Halas"

      - name: Show files
        run: ls -l

      - name: Proceed commit
        run: bash ./bot.sh
        shell: bash
