name: Daily Auto Commits Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9,16 * * *"

jobs:
  daily_auto_commits:
    name: Daily Auto Commits Job
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup git User
        run: |
          git config --global user.email "tolikgalas@gmail.com"
          git config --global user.name "Anatolii Halas"

      - name: Get day of week
        id: day_of_week
        run: echo "weekday=$(date +%A)" >> $GITHUB_OUTPUT

      - name: Set random number of commits
        id: set_min_max_value
        run: |
          weekday=${{ steps.day_of_week.outputs.weekday }}
          if [ $weekday == "Sunday" ] || [ $weekday == "Saturday" ]; then
            echo "min=5" >> $GITHUB_OUTPUT
            echo "max=25" >> $GITHUB_OUTPUT
          else
            echo "min=25" >> $GITHUB_OUTPUT
            echo "max=75" >> $GITHUB_OUTPUT
          fi

      - name: Random number for commits
        id: commits_number
        uses: yakubique/random-number@v1.1
        with:
          min: ${{ steps.set_min_max_value.outputs.min }}
          max: ${{ steps.set_min_max_value.outputs.max }}

      - name: Generate commits random number of times
        id: commits
        run: |
          number_of_commits=${{ steps.commits_number.outputs.number }}
          for((i=0; i<number_of_commits; i++)); do
            info="Commit - $(date)"
            echo "$info" >> reports.txt
            git commit -am "$info"
            sleep 0.5
          done
          git push
          exit 0

      - name: Notify Slack - Success
        uses: slackapi/slack-github-action@v1.26.0
        if: ${{ steps.commits.outcome.status == 'success' }}
        with:
          payload: |
            {
              "text": "Automated commits published successfully ✅"
              "blocks": {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Github Action 'Daily Auto Commits Workflow' job result: ${{ job.status }}\nNumber of commits published: ${{ steps.commits_number.outputs.number }}"
                }
              }
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack - Failure
        uses: slackapi/slack-github-action@v1.26.0
        if: ${{ steps.commits.outcome.status == 'failure' }}
        with:
          payload: |
            {
              "text": "Automated commits publish failed ❌"
              "blocks": {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Github Action 'Daily Auto Commits Workflow' job result: ${{ job.status }}"
                }
              }
            }
