name: Daily Auto Commits Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  daily_auto_commits:
    name: Daily Auto Commits Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone tolikhalas/commit-bot repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: "main"
          owner: "tolikhalas"
          repository: "commit-bot"

      - name: Setup git user
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "toligalas@gmail.com"
          git config --global user.name "Anatolii Halas"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/tolikhalas/commit-bot.git

      - name: Setup execution permissions
        run: chmod +x ./commit-bot/bot.sh

      - name: Run Autocommit bot
        run: |
          cd commit-bot
          bash bot.sh
