name: Daily Auto Commits Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  daily_auto_commits:
    name: Daily Auto Commits Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: tolikhalas/commit-bot

      - name: Say Hello
        run: echo 'Hello'
